version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
